# Generated by Django 5.0.1 on 2024-01-26 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hw_app', '0002_alter_product_adding_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default=2, upload_to=''),
            preserve_default=False,
        ),
    ]
